{
 "title": "Bitaxe",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ASIC frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_frequency{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_voltage{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_temp{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hash Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_hash_rate{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_power{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_current{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Asic Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_asic_core_voltage{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shares Accepted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_shares_accepted{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shares Rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_shares_rejected{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hash Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "axe_hash_rate{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Hash Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "axe_hash_rate{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hash Rate",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "axe_hash_rate{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "axe_power{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "axe_temp{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "axe_voltage{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Asic Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "axe_asic_core_voltage{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "axe_current{instance=\"10.10.99.1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}