version: "3"
services:
    json-exporter:
        ports:
            - "7979:7979"
        volumes:
            - /root/jsonexporter/config/:/config/
        image: quay.io/prometheuscommunity/json-exporter
        restart: unless-stopped
        command: --config.file=/config/config.yml