modules:
  default:
    metrics:
    - name: axe_power
      path: "{.power}"
      type: value
      help: Power in W
      labels:
        hostname: '{.hostname}'
    - name: axe_voltage
      path: "{.voltage}"
      type: value
      help: Voltage in V
      labels:
        hostname: '{.hostname}'
    - name: axe_asic_core_voltage_setting
      path: "{.coreVoltage}"
      type: value
      help: Core voltage setting in V
      labels:
        hostname: '{.hostname}'
    - name: axe_asic_core_voltage
      path: "{.coreVoltageActual}"
      type: value
      help: Actual Core voltage in V
      labels:
        hostname: '{.hostname}'
    - name: axe_current
      path: "{.current}"
      type: value
      help: Current in mA
      labels:
        hostname: '{.hostname}'
    - name: axe_fan_speed_rpm
      path: "{.fanrpm}"
      type: value
      help: Fan speed in RPM
      labels:
        hostname: '{.hostname}'
    - name: axe_fan_speed_percent
      path: "{.fanspeed}"
      type: value
      help: Fan speed in percentage
      labels:
        hostname: '{.hostname}'
    - name: axe_temp
      path: "{.temp}"
      type: value
      help: Temperature in Celsius
      labels:
        hostname: '{.hostname}'
    - name: axe_hash_rate
      path: "{.hashRate}"
      type: value
      help: Hash rate in GH/s
      labels:
        hostname: '{.hostname}'
    - name: axe_frequency
      path: "{.frequency}"
      type: value
      help: ASIC frequency
      labels:
        hostname: '{.hostname}'
    - name: axe_shares_accepted
      path: "{.sharesAccepted}"
      type: value
      help: Shares accepted
      labels:
        hostname: '{.hostname}'
    - name: axe_shares_rejected
      path: "{.sharesRejected}"
      type: value
      help: Shares rejected
      labels:
        hostname: '{.hostname}'
    - name: axe_uptime
      path: "{.uptimeSeconds}"
      type: value
      help: Uptime in seconds
      labels:
        hostname: '{.hostname}'
    - name: axe_vr_temp
      path: "{.vrTemp}"
      type: value
      help: Voltage regulator temperature in Celsius
      labels:
        hostname: '{.hostname}'
    - name: axe_free_heap
      path: "{.freeHeap}"
      type: value
      help: Free heap memory in Bytes
      labels:
        hostname: '{.hostname}'
    - name: axe_overheat_mode
      path: "{.overheat_mode}"
      type: value
      help: Overheated false/true
      labels:
        hostname: '{.hostname}'
    - name: axe_best_difficulty
      path: "1"
      type: value
      help: Best difficulty
      labels:
        hostname: '{.hostname}'
        difficulty: '{.bestDiff}'
    - name: axe_best_session_difficulty
      path: "1"
      type: value
      help: Best difficulty since boot
      labels:
        hostname: '{.hostname}'
        difficulty: '{.bestSessionDiff}'
    - name: axe_stratum_url
      path: "1"
      type: value
      help: Stratum URL
      labels:
        hostname: '{.hostname}'
        stratum_url: '{.stratumURL}'
    - name: axe_wifi_status
      path: "1"
      type: value
      help: WIFI Status
      labels:
        hostname: '{.hostname}'
        wifi_status: '{.wifiStatus}'
